repos:
-   repo: local
    hooks:
    -   id: dev-script-pre-push
        name: pre-push dev script hook
        stages: [pre-push]
        language: system
        entry: bash -c "{ echo; ./dev; } > /dev/tty 2>&1"  # Hack for real-time output
        pass_filenames: false  # otherwise would run on a per-file basis
        verbose: true

