repos:
- repo: local
  hooks:
    - id: ruff-format
      name: ruff-format
      entry: uvx ruff format
      language: system
      types: [python]

    - id: ty-check
      name: ty-check
      entry: uvx ty check
      language: system
      types: [python]

    - id: pytest-cov
      name: pytest-cov
      entry: uv run pytest --cov
      language: system
      pass_filenames: false   # run full test suite, not just staged files
