# .pre-commit-config.yaml
repos:
-   repo: local
    hooks:
    -   id: run-dev-script-pre-push
        name: Run dev script before push
        entry: ./dev
        language: python
        stages: [pre-push]

